// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: proto/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
//
//	ENTITIES
//
// =====================
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CartId        uint32                 `protobuf:"varint,3,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Address       *AddressSnapshot       `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Products      []*ProductSnapshot     `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // pending | paid | failed | cancelled
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        string                 `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetCartId() uint32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *Transaction) GetAddress() *AddressSnapshot {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Transaction) GetProducts() []*ProductSnapshot {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Transaction) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type AddressSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     uint32                 `protobuf:"varint,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressSnapshot) Reset() {
	*x = AddressSnapshot{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSnapshot) ProtoMessage() {}

func (x *AddressSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSnapshot.ProtoReflect.Descriptor instead.
func (*AddressSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *AddressSnapshot) GetAddressId() uint32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *AddressSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressSnapshot) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ProductSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Qty           uint32                 `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Subtotal      int64                  `protobuf:"varint,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	CategoryId    uint32                 `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSnapshot) Reset() {
	*x = ProductSnapshot{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSnapshot) ProtoMessage() {}

func (x *ProductSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSnapshot.ProtoReflect.Descriptor instead.
func (*ProductSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ProductSnapshot) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSnapshot) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductSnapshot) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *ProductSnapshot) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *ProductSnapshot) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

// =====================
//
//	REQUESTS
//
// =====================
type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CartId        uint32                 `protobuf:"varint,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	AddressId     uint32                 `protobuf:"varint,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransactionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTransactionRequest) GetCartId() uint32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CreateTransactionRequest) GetAddressId() uint32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type ListTransactionByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionByUserRequest) Reset() {
	*x = ListTransactionByUserRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionByUserRequest) ProtoMessage() {}

func (x *ListTransactionByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionByUserRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionByUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTransactionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionRequest) Reset() {
	*x = ListTransactionRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionRequest) ProtoMessage() {}

func (x *ListTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransactionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarkAsPaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // transaction_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsPaidRequest) Reset() {
	*x = MarkAsPaidRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsPaidRequest) ProtoMessage() {}

func (x *MarkAsPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsPaidRequest.ProtoReflect.Descriptor instead.
func (*MarkAsPaidRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAsPaidRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionRequest) Reset() {
	*x = CancelTransactionRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionRequest) ProtoMessage() {}

func (x *CancelTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionRequest.ProtoReflect.Descriptor instead.
func (*CancelTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTransactionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CancelTransactionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// =====================
//
//	RESPONSES
//
// =====================
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ListTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionResponse) Reset() {
	*x = ListTransactionResponse{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionResponse) ProtoMessage() {}

func (x *ListTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetAllTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTransactionsResponse) Reset() {
	*x = GetAllTransactionsResponse{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTransactionsResponse) ProtoMessage() {}

func (x *GetAllTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CancelTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransactionResponse) Reset() {
	*x = CancelTransactionResponse{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransactionResponse) ProtoMessage() {}

func (x *CancelTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransactionResponse.ProtoReflect.Descriptor instead.
func (*CancelTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_transaction_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"#proto/transaction/transaction.proto\x12\vtransaction\x1a\x1bgoogle/protobuf/empty.proto\"\xb4\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x17\n" +
	"\acart_id\x18\x03 \x01(\rR\x06cartId\x126\n" +
	"\aaddress\x18\x04 \x01(\v2\x1c.transaction.AddressSnapshotR\aaddress\x128\n" +
	"\bproducts\x18\x05 \x03(\v2\x1c.transaction.ProductSnapshotR\bproducts\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\t \x01(\tR\x06paidAt\"X\n" +
	"\x0fAddressSnapshot\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\rR\taddressId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\"\xa9\x01\n" +
	"\x0fProductSnapshot\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\rR\x03qty\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\x03R\bsubtotal\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\rR\n" +
	"categoryId\"k\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\acart_id\x18\x02 \x01(\rR\x06cartId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\rR\taddressId\"6\n" +
	"\x1cListTransactionByUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\"@\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"1\n" +
	"\x16ListTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"#\n" +
	"\x11MarkAsPaidRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"C\n" +
	"\x18CancelTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"Q\n" +
	"\x13TransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.transaction.TransactionR\vtransaction\"W\n" +
	"\x17ListTransactionResponse\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\ftransactions\"Z\n" +
	"\x1aGetAllTransactionsResponse\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\ftransactions\"5\n" +
	"\x19CancelTransactionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb6\x04\n" +
	"\x12TransactionService\x12\\\n" +
	"\x11CreateTransaction\x12%.transaction.CreateTransactionRequest\x1a .transaction.TransactionResponse\x12V\n" +
	"\x0eGetTransaction\x12\".transaction.GetTransactionRequest\x1a .transaction.TransactionResponse\x12a\n" +
	"\x14ListUserTransactions\x12#.transaction.ListTransactionRequest\x1a$.transaction.ListTransactionResponse\x12S\n" +
	"\x13ListAllTransactions\x12\x16.google.protobuf.Empty\x1a$.transaction.ListTransactionResponse\x12b\n" +
	"\x11CancelTransaction\x12%.transaction.CancelTransactionRequest\x1a&.transaction.CancelTransactionResponse\x12N\n" +
	"\n" +
	"MarkAsPaid\x12\x1e.transaction.MarkAsPaidRequest\x1a .transaction.TransactionResponseB\x14Z\x12proto/transaction/b\x06proto3"

var (
	file_proto_transaction_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_transaction_proto_rawDescData []byte
)

func file_proto_transaction_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_transaction_proto_rawDescData
}

var file_proto_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_transaction_transaction_proto_goTypes = []any{
	(*Transaction)(nil),                  // 0: transaction.Transaction
	(*AddressSnapshot)(nil),              // 1: transaction.AddressSnapshot
	(*ProductSnapshot)(nil),              // 2: transaction.ProductSnapshot
	(*CreateTransactionRequest)(nil),     // 3: transaction.CreateTransactionRequest
	(*ListTransactionByUserRequest)(nil), // 4: transaction.ListTransactionByUserRequest
	(*GetTransactionRequest)(nil),        // 5: transaction.GetTransactionRequest
	(*ListTransactionRequest)(nil),       // 6: transaction.ListTransactionRequest
	(*MarkAsPaidRequest)(nil),            // 7: transaction.MarkAsPaidRequest
	(*CancelTransactionRequest)(nil),     // 8: transaction.CancelTransactionRequest
	(*TransactionResponse)(nil),          // 9: transaction.TransactionResponse
	(*ListTransactionResponse)(nil),      // 10: transaction.ListTransactionResponse
	(*GetAllTransactionsResponse)(nil),   // 11: transaction.GetAllTransactionsResponse
	(*CancelTransactionResponse)(nil),    // 12: transaction.CancelTransactionResponse
	(*emptypb.Empty)(nil),                // 13: google.protobuf.Empty
}
var file_proto_transaction_transaction_proto_depIdxs = []int32{
	1,  // 0: transaction.Transaction.address:type_name -> transaction.AddressSnapshot
	2,  // 1: transaction.Transaction.products:type_name -> transaction.ProductSnapshot
	0,  // 2: transaction.TransactionResponse.transaction:type_name -> transaction.Transaction
	0,  // 3: transaction.ListTransactionResponse.transactions:type_name -> transaction.Transaction
	0,  // 4: transaction.GetAllTransactionsResponse.transactions:type_name -> transaction.Transaction
	3,  // 5: transaction.TransactionService.CreateTransaction:input_type -> transaction.CreateTransactionRequest
	5,  // 6: transaction.TransactionService.GetTransaction:input_type -> transaction.GetTransactionRequest
	6,  // 7: transaction.TransactionService.ListUserTransactions:input_type -> transaction.ListTransactionRequest
	13, // 8: transaction.TransactionService.ListAllTransactions:input_type -> google.protobuf.Empty
	8,  // 9: transaction.TransactionService.CancelTransaction:input_type -> transaction.CancelTransactionRequest
	7,  // 10: transaction.TransactionService.MarkAsPaid:input_type -> transaction.MarkAsPaidRequest
	9,  // 11: transaction.TransactionService.CreateTransaction:output_type -> transaction.TransactionResponse
	9,  // 12: transaction.TransactionService.GetTransaction:output_type -> transaction.TransactionResponse
	10, // 13: transaction.TransactionService.ListUserTransactions:output_type -> transaction.ListTransactionResponse
	10, // 14: transaction.TransactionService.ListAllTransactions:output_type -> transaction.ListTransactionResponse
	12, // 15: transaction.TransactionService.CancelTransaction:output_type -> transaction.CancelTransactionResponse
	9,  // 16: transaction.TransactionService.MarkAsPaid:output_type -> transaction.TransactionResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_transaction_transaction_proto_init() }
func file_proto_transaction_transaction_proto_init() {
	if File_proto_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_transaction_proto = out.File
	file_proto_transaction_transaction_proto_goTypes = nil
	file_proto_transaction_transaction_proto_depIdxs = nil
}
