// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: proto/address/address.proto

package address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	OwnerId       uint32                 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Address) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Address) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	OwnerId       uint32                 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_proto_address_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAddressRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAddressRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateAddressRequest) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_proto_address_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       uint32                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressRequest) Reset() {
	*x = ListAddressRequest{}
	mi := &file_proto_address_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressRequest) ProtoMessage() {}

func (x *ListAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressRequest.ProtoReflect.Descriptor instead.
func (*ListAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{3}
}

func (x *ListAddressRequest) GetOwnerId() uint32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_address_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAddressRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_proto_address_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_proto_address_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{6}
}

func (x *AddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type ListAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressResponse) Reset() {
	*x = ListAddressResponse{}
	mi := &file_proto_address_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressResponse) ProtoMessage() {}

func (x *ListAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressResponse.ProtoReflect.Descriptor instead.
func (*ListAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{7}
}

func (x *ListAddressResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_proto_address_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_address_address_proto protoreflect.FileDescriptor

const file_proto_address_address_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/address/address.proto\x12\aaddress\"{\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\rR\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"Y\n" +
	"\x14CreateAddressRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\rR\aownerId\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"/\n" +
	"\x12ListAddressRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\rR\aownerId\"N\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\"&\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"=\n" +
	"\x0fAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.address.AddressR\aaddress\"E\n" +
	"\x13ListAddressResponse\x12.\n" +
	"\taddresses\x18\x01 \x03(\v2\x10.address.AddressR\taddresses\"1\n" +
	"\x15DeleteAddressResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x84\x03\n" +
	"\x0eAddressService\x12H\n" +
	"\rCreateAddress\x12\x1d.address.CreateAddressRequest\x1a\x18.address.AddressResponse\x12B\n" +
	"\n" +
	"GetAddress\x12\x1a.address.GetAddressRequest\x1a\x18.address.AddressResponse\x12J\n" +
	"\rListAddresses\x12\x1b.address.ListAddressRequest\x1a\x1c.address.ListAddressResponse\x12H\n" +
	"\rUpdateAddress\x12\x1d.address.UpdateAddressRequest\x1a\x18.address.AddressResponse\x12N\n" +
	"\rDeleteAddress\x12\x1d.address.DeleteAddressRequest\x1a\x1e.address.DeleteAddressResponseB\x10Z\x0eproto/address/b\x06proto3"

var (
	file_proto_address_address_proto_rawDescOnce sync.Once
	file_proto_address_address_proto_rawDescData []byte
)

func file_proto_address_address_proto_rawDescGZIP() []byte {
	file_proto_address_address_proto_rawDescOnce.Do(func() {
		file_proto_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_address_address_proto_rawDesc), len(file_proto_address_address_proto_rawDesc)))
	})
	return file_proto_address_address_proto_rawDescData
}

var file_proto_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_address_address_proto_goTypes = []any{
	(*Address)(nil),               // 0: address.Address
	(*CreateAddressRequest)(nil),  // 1: address.CreateAddressRequest
	(*GetAddressRequest)(nil),     // 2: address.GetAddressRequest
	(*ListAddressRequest)(nil),    // 3: address.ListAddressRequest
	(*UpdateAddressRequest)(nil),  // 4: address.UpdateAddressRequest
	(*DeleteAddressRequest)(nil),  // 5: address.DeleteAddressRequest
	(*AddressResponse)(nil),       // 6: address.AddressResponse
	(*ListAddressResponse)(nil),   // 7: address.ListAddressResponse
	(*DeleteAddressResponse)(nil), // 8: address.DeleteAddressResponse
}
var file_proto_address_address_proto_depIdxs = []int32{
	0, // 0: address.AddressResponse.address:type_name -> address.Address
	0, // 1: address.ListAddressResponse.addresses:type_name -> address.Address
	1, // 2: address.AddressService.CreateAddress:input_type -> address.CreateAddressRequest
	2, // 3: address.AddressService.GetAddress:input_type -> address.GetAddressRequest
	3, // 4: address.AddressService.ListAddresses:input_type -> address.ListAddressRequest
	4, // 5: address.AddressService.UpdateAddress:input_type -> address.UpdateAddressRequest
	5, // 6: address.AddressService.DeleteAddress:input_type -> address.DeleteAddressRequest
	6, // 7: address.AddressService.CreateAddress:output_type -> address.AddressResponse
	6, // 8: address.AddressService.GetAddress:output_type -> address.AddressResponse
	7, // 9: address.AddressService.ListAddresses:output_type -> address.ListAddressResponse
	6, // 10: address.AddressService.UpdateAddress:output_type -> address.AddressResponse
	8, // 11: address.AddressService.DeleteAddress:output_type -> address.DeleteAddressResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_address_address_proto_init() }
func file_proto_address_address_proto_init() {
	if File_proto_address_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_address_address_proto_rawDesc), len(file_proto_address_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_address_address_proto_goTypes,
		DependencyIndexes: file_proto_address_address_proto_depIdxs,
		MessageInfos:      file_proto_address_address_proto_msgTypes,
	}.Build()
	File_proto_address_address_proto = out.File
	file_proto_address_address_proto_goTypes = nil
	file_proto_address_address_proto_depIdxs = nil
}
