// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: proto/address/address.proto

package address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_proto_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *GetAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Ownerid       uint32                 `protobuf:"varint,4,opt,name=ownerid,proto3" json:"ownerid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_proto_address_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_address_proto_rawDescGZIP(), []int{1}
}

func (x *GetAddressResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAddressResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAddressResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetAddressResponse) GetOwnerid() uint32 {
	if x != nil {
		return x.Ownerid
	}
	return 0
}

var File_proto_address_address_proto protoreflect.FileDescriptor

const file_proto_address_address_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/address/address.proto\x12\x04user\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"f\n" +
	"\x12GetAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x18\n" +
	"\aownerid\x18\x04 \x01(\rR\aownerid2U\n" +
	"\x0eaddressService\x12C\n" +
	"\x0eGetAddressByID\x12\x17.user.GetAddressRequest\x1a\x18.user.GetAddressResponseB\x10Z\x0eproto/address/b\x06proto3"

var (
	file_proto_address_address_proto_rawDescOnce sync.Once
	file_proto_address_address_proto_rawDescData []byte
)

func file_proto_address_address_proto_rawDescGZIP() []byte {
	file_proto_address_address_proto_rawDescOnce.Do(func() {
		file_proto_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_address_address_proto_rawDesc), len(file_proto_address_address_proto_rawDesc)))
	})
	return file_proto_address_address_proto_rawDescData
}

var file_proto_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_address_address_proto_goTypes = []any{
	(*GetAddressRequest)(nil),  // 0: user.GetAddressRequest
	(*GetAddressResponse)(nil), // 1: user.GetAddressResponse
}
var file_proto_address_address_proto_depIdxs = []int32{
	0, // 0: user.addressService.GetAddressByID:input_type -> user.GetAddressRequest
	1, // 1: user.addressService.GetAddressByID:output_type -> user.GetAddressResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_address_address_proto_init() }
func file_proto_address_address_proto_init() {
	if File_proto_address_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_address_address_proto_rawDesc), len(file_proto_address_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_address_address_proto_goTypes,
		DependencyIndexes: file_proto_address_address_proto_depIdxs,
		MessageInfos:      file_proto_address_address_proto_msgTypes,
	}.Build()
	File_proto_address_address_proto = out.File
	file_proto_address_address_proto_goTypes = nil
	file_proto_address_address_proto_depIdxs = nil
}
